INSERT INTO PERSONAL (
  	name,
  	preferredName,
  	title,
	namePrefix,
	nameSuffix,
	qualificationCode,
	maidenName,
	hrID,
	studentId,
	telephoneNumber,
	primaryPhoneNumber,
	birthdate,
	email,
	emailType,
	citizenship,
	veteran,
	sex,
	primaryLanguage,
	emergencyContact,
	address,
	addressTwo)
	VALUES (
'Alice Beth Smith',
'Alice Smith',
'',
'',
'',
'',
'Smith',
'0987654321',
'1234567890',
'(480) 555-1234',
'Yes',
'July 4, 1985',
'alice.smith@us.af.mil',
'Organization',
'American Citizen',
'Y',
'F',
'English',
'Smith S. Smithson (480) 555-1234',
'123 Taft St, Crystal City, VA 22201',
'Apartment 205'
);
INSERT INTO ORGANIZATION (
  	organizationName,
	industryIdentifier,
	parentOrganization,
	accreditationType,
	organizationIdentifier,
	organizationFEIN,
	organizationAccredits,
	accreditationAwardDate,
	organizationIdentificationCode,
	organizationDescription,
	accreditedBy,
	accreditedExpirationDate)
	VALUES(
	'AETC',
	'',
	'Air Force',
	'Lorem Ipsum',
	'D0DAF', 
	'00001234567',
	'Yes',
	'01/01/2000',
	'G0V4', 
	'D0D Air Force', 
	'Lorem Ipsum', 
	'XX/XX/XXXX'
	);